//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories
    {
        public int AccessoryID { get; set; }
        public string AccessoryNameDescription { get; set; }
        public string PhotoLink { get; set; }
        public string ColorPrimary { get; set; }
        public string ColorSecondary { get; set; }
        public string ColorTertiary { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }
    }
}
