//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeProjectDBEntities : DbContext
    {
        public WardrobeProjectDBEntities()
            : base("name=WardrobeProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accessories> Accessories { get; set; }
        public DbSet<Bottoms> Bottoms { get; set; }
        public DbSet<Shoes> Shoes { get; set; }
        public DbSet<Tops> Tops { get; set; }
    }
}
